### ISSUE TITLE
Business Statement Report

### ISSUE THREAD

**Issue by elifmerve** [IMPETUSCO/Design-Project#1]
Here is the place where we discuss the items related wityh bussines statement report.
Let us start by putting the link from capstone eee.

http://capstone.eee.metu.edu.tr/business-statement/

**Comment by elifmerve** [comment]
Arkadaşlar, cvlerimizin aynı olması için Emre bir templete üstünde uğraşıyor. Bittiği zaman yükleyecek ve sizden de cvleri ona göre düzenlemenizi istiyor.

**Comment by elifmerve** [comment]
CV templete yüklenmiştir. Business statement report klasörünün altını kontrol eder misiniz?

**Comment by elifmerve** [comment]
Introduction: IMPETUS Corporation was established in September 2019 by five electrical and electronics engineering students at Middle East Technical University. The very first meeting of the company members took place at Çatı Cafe. The goal which brings the company members together is to produce intelligent solutions to everyday problems. 
	The company pays attention to collect people from different fields of electrical and electronics engineering. The main specializations of the members are electronics, power electronics, and control. This field division among the members helps the company to come up with distinguished approaches to various problems, as well as to create an opportunity for the members to work on their area of specialization.

**Comment by edsenel** [comment]
Business statement için aşağıdakiler yazılacak.

Cat Feeding System - Elif Merve
Vale Parking - Emre Deniz
Gimme Fast - Yunus
Where am I - Melike
Conclusion - Fahri

**Comment by elifmerve** [comment]
SMART CONNECTED CAT FEEDING AND MONITORING SYSTEM

	Smart connected cat feeding system is one of the projects that is assigned to EE493 students. The system must be autonomous, smart and refillable. The goal of the system is to overcome problems of manual feeding.
              First of all, the system should feed only cats. If there are dogs in the feeding area, the system should distinguish and deter them from the area. The system should have a database which is some kind of feeding log. Thus, newcomers to feeding should be identified and recognized later by the system. Cats must be classified according to their weights so that different feeding regimes can be applied to them. Nothing can be attached to the animals. Because the same system can be used in different areas. Status of food supply should be observable via the internet.
The system is designed to make feeding easier. During the operation or charging, the battery level can be seen via the internet, too. So, it should be portable enough to be carried by a single person to charge it in case of a low battery. Battery should be non-removable and last for a minimum of 5 hours.

**Comment by elifmerve** [comment]
SMART CONNECTED CAT FEEDING AND MONITORING SYSTEM : Smart connected cat feeding system is one of the projects that is assigned to EE493 students. The system must be autonomous, smart and refillable. The goal of the system is to overcome problems of manual feeding.
              First of all, the system should feed only cats. If there are dogs in the feeding area, the system should distinguish and deter them from the area. The system should have a database which is some kind of feeding log. Thus, newcomers to feeding should be identified and recognized later by the system. Cats must be classified according to their weights so that different feeding regimes can be applied to them. Nothing can be attached to the animals. Because the same system can be used in different areas. Status of food supply should be observable via the internet.
The system is designed to make feeding easier. During the operation or charging, the battery level can be seen via the internet, too. So, it should be portable enough to be carried by a single person to charge it in case of a low battery. Battery should be non-removable and last for a minimum of 5 hours.
