### ISSUE TITLE
Upload Your Course Schedule

### ISSUE THREAD

**Issue by elifmerve** [IMPETUSCO/Design-Project#4]
Please upload your course schedules to arrange meeting with our advisor.

**Comment by elifmerve** [comment]
I'm not going to lectures of section 3. So I've added section 1's lecture hours by hand. 

![elif_schedule](https://user-images.githubusercontent.com/38141251/66204849-887e6f80-e6b4-11e9-86cb-15302c385e5d.jpg)

**Comment by edsenel** [comment]
Başka labım yok bütün programım böyle
![schedule_eds](https://user-images.githubusercontent.com/48822867/66206466-e1500700-e6b8-11e9-9f1d-8a997e387aeb.png)

**Comment by yunusyilmaz-metu** [comment]
Kırmızı ile işaretlediğim yerlerde dersim yok. Mavi ile işaretlediğim yerde 361 labım var. 361 de 2. Sectiona gittiğim için onun saatlerini ekledim. 


Emre Deniz Şenel <notifications@github.com> şunları yazdı (4 Eki 2019 15:09):

**Comment by Fahrizo** [comment]
Cuma sabahı 4 saat EE463 labım var programa eklediğim üzere
![my_schedule](https://user-images.githubusercontent.com/55561765/66242071-68c56680-e709-11e9-9cb4-5b4ea7648dd2.png)

**Comment by yunusyilmaz-metu** [comment]
![WhatsApp Image 2019-10-04 at 16 24 27](https://user-images.githubusercontent.com/55561672/66254556-78cc5d00-e780-11e9-81e3-40f563c778d1.jpeg)

Önceki attığım mesajda görselde bir sıkıntı olmuş o yüzden tekrarlıyorum.  Kırmızı ile işaretlediğim yerlerde dersim yok. Mavi ile işaretlediğim yerde 361 labım var. 361 de 2. Sectiona gittiğim için onun saatlerini ekledim.

**Comment by elifmerve** [comment]
Fixes #4

**Comment by melike** [comment]
[CourseSchedule_2019.pdf](https://github.com/IMPETUSCO/IMPETUS-Project-1/files/3697731/CourseSchedule_2019.pdf)
