### ISSUE TITLE
Weekly Report #1

### ISSUE THREAD

**Issue by elifmerve** [IMPETUSCO/Design-Project#5]

**Comment by elifmerve** [comment]
Rapora fotograflarımızı koymamız için herkes edsenel@gmail.com'a vesikalıklarını gönderebilir mi?

**Comment by melike** [comment]
Ekte örnek bulunuyor.
[weekly lab report template.docx](https://github.com/IMPETUSCO/IMPETUS-Project-1/files/3697808/weekly.lab.report.template.docx)

**Comment by Fahrizo** [comment]
Weekly Report #1 in tamamlanmamış hali Weekly Reports klasörüne eklendi. Hocaya soracağımız sorular kısmı doldurulacak.

**Comment by elifmerve** [comment]
Hocaya sorulacak birkaç şeyi yunusun defterine yazmıştık aslında. Onlar duruyor mu? @yunusyilmaz-metu

**Comment by yunusyilmaz-metu** [comment]
Evet duruyorlar. Bazıları projeyle seçimiyle doğrudan ilgili olsa da sorular şöyle:
1-Grid akıllı olabilir mi?
2-Projede Arduino kullanılabilir mi? Yoksa bütün işi Raspberry Pi üzerinden mi yapmamız gerekiyor?
3-Gridler simetrik olmalı mı?
4-Araçların park halindeki yönelimleri aynı olmalı mı?
5-Ortadaki aracı, diğer araçları yerlerinden oynatmadan çıkarabilir miyiz?
6-Çizgi izletebilir miyiz?
7-Duvarımız olabilirmi?

Aynı zamanda bazı fikirler öne sürmüştük daha önceki toplantımızda:
1-Vale grid büyüklüğünde olup çizgi izleyerek park noktalarını bulacak, araç havada taşınacak.
2-Vinç sistemiyle araç kaldırılarak taşınacak.
