### ISSUE TITLE
Proje  Seçimi İçin Ağırlıklı Tablo Maddeleri 

### ISSUE THREAD

**Issue by edsenel** [IMPETUSCO/Design-Project#7]
Buraya uygun gördüğünüz başlıkları yazabilirsiniz.

**Comment by edsenel** [comment]
1. Software Based
2. Hardware Based
3. Profitability
4. Adoptability to everyday life
5. Interdisciplinary
6. Enjoyable
7. Open to improvement

**Comment by yunusyilmaz-metu** [comment]
1. Software based
2. Hardware based
3. Mechanic based
4. Profitability
5. Communication based
6. Multidisciplinary*
7. Image processing workload
8. Adoptability to everyday life
9. Enjoyable

**Comment by melike** [comment]
1. Mechanics
2. Electronics
3. Image Processing
4. Control
5. Communication
6. Software-User Interface
7. Multidisciplinary
8. Enjoyable

**Comment by Fahrizo** [comment]
1.Realistic
2.Applicable
3.Environmental Friendly
4.Multidisciplinary
5.Improvable
6.Control
7.Software
8.Mechanics
9.Cost
10.Marketable
11.Probability of Success :)

**Comment by melike** [comment]
Probability of Success bence hepsi 10 çünkü ne olursa olsun yapacağız mecbur :)

**Comment by Fahrizo** [comment]
Ben Where am I ve Gimme Fast için aynı fikirde değilim :) Gimme Fast o kadar değil de Where am I...

**Comment by elifmerve** [comment]
Achievable in bounded time
Marketable

**Comment by Fahrizo** [comment]
Selections are done.
